development:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000

test:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000
